sample-proj/config/routes.rb
Rails.application.routes.draw do
    
resources :welcomes do
member do
get :delete
end
end

   root 'welcomes#index'

end

sample-proj/app/models/welcome.rb
class Welcome < ActiveRecord::Base

validates_presence_of :name, :password

def self.some_method(id)
find(id)

end
end

sample-proj/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

sample-proj/app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index 
   @welcomes = Welcome.all
  end
  def new
    @welcome = Welcome.new
  end
  def create
   @welcome =Welcome.new(welcome_params)
   if @welcome.save    
   flash[:notice] = "saved successfully"
   redirect_to welcomes_path
   else
   flash[:error] = @welcome.errors.full_messages.to_sentence
   render "new"
  end
end
  def edit
     @welcome = Welcome.some_method(params[:id])
   end
  def update
		@welcome = Welcome.some_method(params[:id])
		if @welcome.update_attributes(welcome_params)
			flash[:notice] = "Updated successfully"
			redirect_to welcomes_path
    else
			flash[:error] = "editpage error"
			render "new"
		end
  end
  def delete
@welcomes = Welcome.all
    @welcome = Welcome.find(params[:id])
    if @welcome.destroy
     flash[:notice] = "delete successfully"
     render "index"
    else 
     flash[:error] = "not delete"
     render "index"
   end
end
private
	def welcome_params
	params.require(:welcome).permit(:name, :password)
end
end

sample-proj/app/helpers/application_helper.rb
module ApplicationHelper
end

sample-proj/app/helpers/welcome_helper.rb
module WelcomeHelper
end

sample-proj/app/views/welcomes/_form.html.erb
<p><%= f.label :Name %><br>
	<%= f.text_field :name %>
	</p>
	<p>
	<%= f.label :Password %><br>
	<%= f.text_field :password %>
        </p>

sample-proj/app/views/welcomes/edit.html.erb
<h1>Edit page</h1>

<%= form_for @welcome,:html => { :method => :put} do |f| %>
	<%= render "form", f: f %>
	<%= f.submit "Update" %>
        
<% end %>

sample-proj/app/views/welcomes/index.html.erb
<%= flash[:notice]%>
<% @welcomes.each do |f| %>
<p><%= f.name %> ||
<%= f.password %>
<%= link_to "delete" , controller: "welcomes", action: "delete",id: f.id%>
<%= link_to "edit",edit_welcome_path(f.id) %>
</p>
<% end %>
<%= link_to "new",new_welcome_path%>

sample-proj/app/views/welcomes/new.html.erb
<h1>Hai</h1>

<%= flash[:error]%>
<%= form_for :welcome, url: "/welcomes", method: :post do |f| %>
	<%= render "form", f: f %>
	<%= f.submit "create" %>
<% end %>